{% set name = "gaitpy" %}
{% set version = "1.6.1" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/matt002/{{ name }}/archive/{{ version }}.tar.gz
  sha256: aee5b18a257a37f6a68fd14c1ef55fb784fe0e73d31782a9080c9611557fd5b2

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python ==3.6
    - pip
    - setuptools
    - numpy ==1.13.3
    - pandas ==0.20.3
    - scipy ==1.2.0
    - PyWavelets ==0.5.2
    - scikit-learn ==0.21.3
    - statsmodels ==0.8.0
    - bokeh ==0.12.10
    - dill ==0.2.7.1
    - deepdish ==0.3.4
  run:
    - python ==3.6
    - numpy ==1.13.3
    - pandas ==0.20.3
    - scipy ==1.2.0
    - PyWavelets ==0.5.2
    - scikit-learn ==0.21.3
    - statsmodels ==0.8.0
    - bokeh ==0.12.10
    - dill ==0.2.7.1
    - deepdish ==0.3.4

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs gaitpy

about:
  home: https://github.com/matt002/GaitPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A python package for gait analysis using an accelerometer on the lower back'
  description: |
    GaitPy provides python functions to read accelerometry data from a single lumbar-mounted sensor and estimate clinical characteristics of gait. GaitPy has been tested using python v3.6.
  doc_url: https://matt002.github.io/GaitPy/html/index.html
  dev_url: https://github.com/matt002/GaitPy

extra:
  recipe-maintainers:
    - matt002
